apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
      version: blue
  template:
    metadata:
      labels:
        app: game-service
        version: blue
    spec:
      containers:
      - name: game-service
        image: nadeesha171/game-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
      version: green
  template:
    metadata:
      labels:
        app: game-service
        version: green
    spec:
      containers:
      - name: game-service
        image: nadeesha171/game-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: NodePort
  selector:
    app: game-service
    version: blue
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
