apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: YW5hbHl0aWNzZGI=        # base64 for "analyticsdb"
  POSTGRES_USER: cG9zdGdyZXM=          # base64 for "postgres"
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # base64 for "mypassword"
