name: Build and push Docker images

on:
  push:
    branches: [ main ]   # triggers when you push to main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ frontend, game-service, order-service, analytics-service ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            nadeesha171/${{ matrix.service }}:latest
            nadeesha171/${{ matrix.service }}:${{ github.sha }}
